version: "3.9"
services:
  minio:
    command: ./minio server /data --console-address ":9001"
    build: .
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=uploader
      - POSTGRES_USER=uplser
      - POSTGRES_PASSWORD=R!QM@3%un4!R
    container_name: postgres_db
  app:
    build: .
    ports:
    - 8000:8000
    image: app:uploader_project
    container_name: django_uploader_container
    command: >
      bash -c "python manage.py migrate
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db