# Generated by Django 3.2.11 on 2022-01-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_extension',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Extension'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.IntegerField(default=0, verbose_name='Size'),
        ),
    ]
